# Generated by Django 5.0.4 on 2024-04-09 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=256)),
                ('format', models.CharField(max_length=256)),
                ('language', models.CharField(max_length=256)),
                ('publish_year', models.IntegerField()),
            ],
        ),
    ]
